version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=SuaSenhaForte@123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:80"
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
