# Base image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia os arquivos do projeto
COPY ["ApiSuporteInteligente.csproj", "./"]
RUN dotnet restore "ApiSuporteInteligente.csproj"
COPY . .
RUN dotnet build "ApiSuporteInteligente.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ApiSuporteInteligente.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ApiSuporteInteligente.dll"]
